### PR TITLE
Draft reactive sidechain

### PR DESCRIPTION
**Pull request by diogomart**

### CODE REVIEW

**Comment by rwxayheee** [comment]
(Summary of this PR)
After [25b2357](https://github.com/forlilab/Meeko/pull/157/commits/25b23579fbc61e2d5e9c56fefc8a921ace601e75), mk_prepare_receptor.py now returns exact same _flex.pdbqt output as the previous temporary fix [a39b701](https://github.com/rwxayheee/Meeko/commit/a39b701ba5cd6107f5536ce2383ba3c0888bdff9)

Major changes are: 
## 1. complete removal of openbabel dependency
The removed components include: 
(1) Library file `obutils.py`
(2) Relevant Class (`OBMoleculeSetup`) and function (`copy_coordinates_to_obmol`)
(3) Relevant backend option in `mk_prepare_ligand.py`
(4) Relevant module usage and check (`_has_openbabel`)
(5) Relevant template (`-i`, `--original_input`) option in `mk_export.py`

## 2. track and replace usage of PDBQTReceptor and others from meeko/receptor_pdbqt.py with equivalents from meeko/linked_rdkit_chorizo.py
The PR replaced usage of PDBQTReceptor in mk_prepare_receptor.py by equivalents in `reactive.py`. After the changes, the only remaining script that expects PDBQTReceptor is: 
`Meeko/meeko/analysis/interactions.py`
and
`Meeko/meeko/analysis/fingerprint_interactions.py`

## 3. enable handling of certain blunt_end without user intervention
The PR used a quick fix to allow all link atoms to be a blunt_end. Before, residues that are immediately before a gap must be handled by "--allow_bad_res". Now, these residues (if fully resolved themselves) will present in the output PDBQT file with auto blunt ends. 

## 4. make meaningful syntax changes for --reactive_flexres
The previous temporary fix [a39b701](https://github.com/rwxayheee/Meeko/commit/a39b701ba5cd6107f5536ce2383ba3c0888bdff9) supported the following old syntax: 
```
mk_prepare_receptor.py --pdb 1d3g_input/1d3g_receptor.pdb --allow_bad_res \
--ligand 1d3g_input/1d3g_FMN.pdb --padding 2 \
--reactive_flexres "A:LYS:100" \
--reactive_flexres "A:LYS:255" \
--flexres "A:145,356" \
--reactive_name "LYS:CG" \
--reactive_name_specific "A:LYS:255:NZ" \
--output_filename 1d3g_output_1
```
Now, the following new syntax is supported: 
```
mk_prepare_receptor.py --pdb 1d3g_input/1d3g_receptor.pdb --allow_bad_res \
--ligand 1d3g_input/1d3g_FMN.pdb --padding 2 \
--reactive_flexres "A:100,255" \
--flexres "A:145,356,100" \
--reactive_name "LYS:CG" \
--reactive_name_specific "A:255=NZ" \
--output_filename 1d3g_output_2
```

To ensure a working reactive docking workflow with Meeko, two more changes to the other command line tools are planned: 
(1) Small fix to support reactive atom typing in mk_prepare_ligand.py
https://github.com/forlilab/Meeko/issues/160

(2) Support for reactive docking output processing in mk_export.py
This will be added on top of validated changes in ligand preparation and docking tests

**Comment by rwxayheee** [comment]
[5f2f1bd](https://github.com/forlilab/Meeko/pull/157/commits/5f2f1bdfbf662b4c21ff89104bd0eb73bff0044a) has some minor fixes to the command line scripts. Here's a summary: 

## 1.  About mk_prepare_ligand.py
(1) removed args.template_filename (which should have been removed with the other babel-related functionalities)
(2) enabled individual output for all setups in the specified output location, with a suffix of `_mk<index of setup>.pdbqt`. 

## 2. About mk_prepare_receptor.py
(1) writing a gpf: removed path of the rigid receptor file
(2) writing a vina box: round sizes and coordinates to 3 decimal places
(2) updated help msg, commented the modified parts and used black formatting

The changed version passed some basic reactive docking tests. Here're the examples: 
[3kgd_input.zip](https://github.com/user-attachments/files/16901128/3kgd_input.zip)
[3kgd_prepare.zip](https://github.com/user-attachments/files/16901129/3kgd_prepare.zip)
[3kgd_dockoutputs.zip](https://github.com/user-attachments/files/16901141/3kgd_dockoutputs.zip)

**Review by rwxayheee — APPROVED** [review]
The PR has enabled new syntax for receptor preparation and has important improvement  to support ligand preparation for reactive docking. I would like to approve this PR. 
Thank you @diogomart for the great work. Please feel free to merge whenever you're ready

**Comment by diogomart** [comment]
Thank you @rwxayheee this looks great!

**Pull request merged**
