### PR TITLE
Beautify output of mk_prepare_receptor for some failures, rename allowed_altloc to default_altloc

### PR DESCRIPTION
**Pull request by diogomart**
Renamed `allowed_altloc` to `default_altloc`

When residues fail to match templates or altlocs needed to be specified, there's a prettier help message instead of the error traceback. For example:

```
Have alternate location ['A:371']
Either specify an altloc for each with option `wanted_altloc`
or a general default altloc with option `default_altloc`.

Creation of data structure for receptor failed.

Handle AltLocs with default_altloc or wanted_altloc

Use -a/--allow_bad_res to automatically remove residues
that do not match templates, and --default_altloc to set
a default altloc variant. Use these at your own risk.

Inspecting and fixing the input structure is recommended.
Use --wanted_altloc to set variants for specific residues.
```

### CODE REVIEW

**Comment by rwxayheee** [comment]
Hi @diogomart 
The improvements make sense to me. I have a minor edition for `handle_parsing_situations` with some subtle changes to the command line script, where messages from ChorizoCreationError are printed. I feel that the error messages are informative, but there's a little repetition in them and not sure where to look at. Also for `res_needed_altloc` and `res_missed_altloc` if they're critical errors, then the messages might not belong to logger.warning. 

Do you like the following layout? If so see the end of this reply
```
[14:45:06] product atom-mapping number 11 not found in reactants.
[14:45:06] product atom-mapping number 12 not found in reactants.
[14:45:06] product atom-mapping number 11 not found in reactants.
[14:45:06] product atom-mapping number 12 not found in reactants.
[14:45:06] product atom-mapping number 13 not found in reactants.

Error: Creation of data structure for receptor failed.

Details: 
- Template matching failed for: ['A:234', 'A:235', 'A:478']
These residues can be ignored with option allow_bad_res.
- Residues with alternate location: ['A:500', 'A:307']
Either specify an altloc for each with option wanted_altloc
or a general default altloc with option default_altloc.

Recommendations: 
1. (for batch processing) Use -a/--allow_bad_res to automatically remove residues
that do not match templates, and --default_altloc to set
a default altloc variant. Use these at your own risk.

2. (processing individual structure) Inspecting and fixing the input structure is recommended.
Use --wanted_altloc to set variants for specific residues.
```

This is maybe more of a personal reference. Not a big problem, don't feel pressured to change. I will approve after I look at the conflicts


In [linked_rdkit_chorizo]: 
```py
def handle_parsing_situations(
    unmatched_res,
    unparsed_res,
    allow_bad_res,
    res_missed_altloc,
    res_needed_altloc,
    ):

    err = ""
    if unparsed_res:
        msg = f"- Parsing failed for: {unparsed_res}."
        if not allow_bad_res:
            err += msg + os_linesep
        else: 
            msg += " Ignored due to allow_bad_res."
            logger.warning(msg)

    if unmatched_res:
        msg = f"- Template matching failed for: {list(unmatched_res)}"
        if not allow_bad_res:
            err += msg + os_linesep
        else:
            msg += " Ignored due to allow_bad_res."
            logger.warning(msg)

    if err:
        err += "These residues can be ignored with option allow_bad_res." + os_linesep

    if res_needed_altloc: 
        msg = f"- Residues with alternate location: {res_needed_altloc}" + os_linesep
        msg += "Either specify an altloc for each with option wanted_altloc" + os_linesep
        msg += "or a general default altloc with option default_altloc."
        err += msg

    if res_missed_altloc:
        msg = f"- Requested altlocs not found for: {res_missed_altloc}." + os_linesep
        err += msg

    if err:
        raise ChorizoCreationError(err)
    return
```

In [mk_prepare_receptor]
```py
        except ChorizoCreationError as err:
            print()
            print("Error: Creation of data structure for receptor failed.")
            print()
            print("Details: ")
            print(err)
            print()
            print("Recommendations: ")
            print("1. (for batch processing) Use -a/--allow_bad_res to automatically remove residues")
            print("that do not match templates, and --default_altloc to set")
            print("a default altloc variant. Use these at your own risk.")
            print()
            print("2. (processing individual structure) Inspecting and fixing the input structure is recommended.")
            print("Use --wanted_altloc to set variants for specific residues.")
            sys.exit(1)
```

**Review by rwxayheee — APPROVED** [review]
The conflict is because the branch was created before #191. If you could add these changes to this branch it should be conflict-free. I approve the PR

**Comment by diogomart** [comment]
@rwxayheee I really like your output, do you want to push that?

**Comment by diogomart** [comment]
conflicts resolved by merging develop onto here (cli_flags_output_design), @rwxayheee you can push your nice output that you suggested above directly to branch `cli_flags_output_design` on this repo

**Comment by rwxayheee** [comment]
Will do! Thanks. If you have other changes you can keep working on the branch. I will add mine a little later this afternoon.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
